In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [11]:
# Question 1

import numpy as np

randomArray = np.random.randint(1,21, size = 15)
#randomArray = np.random.random(15)

print(f"The random vector: {randomArray}")

# To reshape the array
reshapedArray = randomArray.reshape(3,5)
print(f"The reshaped Array: {reshapedArray}")

# To Print Array shape
print(f"Array shape: {reshapedArray.shape}")

# To replace the max in each row by 0
for i in range(3):
  maxIndex = np.argmax(reshapedArray[i])
  reshapedArray[i,maxIndex] = 0

print(f"Replaced array: {reshapedArray}")



The random vector: [16 11  2  7 13 13  9 13 18  3 15 14  2 10 15]
The reshaped Array: [[16 11  2  7 13]
 [13  9 13 18  3]
 [15 14  2 10 15]]
Array shape: (3, 5)
Replaced array: [[ 0 11  2  7 13]
 [13  9 13  0  3]
 [ 0 14  2 10 15]]


In [17]:
# Question 2

import numpy as np

# Create a 2D array
#array2D = np.zeros((4,3), dtype = np.int32)
array2D = np.random.randint(1,101 ,size = (4,3), dtype=np.int32)

print(f"The 2D Array: {array2D}")
print(f"The shape of the array: {array2D.shape}")
print(f"The Type of the array: {type(array2D)}")
print(f"The Data type of the array: {array2D.dtype}")

The 2D Array: [[56 29 41]
 [80 52 82]
 [96 74 80]
 [72 65 19]]
The shape of the array: (4, 3)
The Type of the array: <class 'numpy.ndarray'>
The Data type of the array: int32


In [18]:
# Question 3

import numpy as np

array = np.array([[0,1,2],
                  [3,4,5]])

sumOfDiagonal = np.trace(array)

print(f"The sum of diagonal elements of the array is: {sumOfDiagonal}")

The sum of diagonal elements of the array is: 4


In [14]:
from re import A
# Question 4

import numpy as np

arrayEven = np.arange(10, 71, 2)
arrayOdd = np.arange(11, 71, 2)

arrayOddEven = np.concatenate((arrayEven, arrayOdd))

print(f"Array of odd and even: {arrayOddEven}")

# Mathematical operations

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(f"The Addition: {a + b}")
print(f"The Substraction: {a - b}")
print(f"The Multiplication: {a * b}")

# Sort

array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

row = np.sort(array, axis = 1)
column = np.sort(array, axis = 0)

print("Array sorted by row: ")
print(row)
print("Array sorted by column: ")
print(column)

Array of odd and even: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43
 45 47 49 51 53 55 57 59 61 63 65 67 69]
The Addition: [ 7  9 11 13 15]
The Substraction: [-5 -5 -5 -5 -5]
The Multiplication: [ 6 14 24 36 50]
Array sorted by row: 
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Array sorted by column: 
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [16]:
# Question 5

array = np.array([[4, 2, np.nan, 1],
                  [11, 12, 14, 9],
                  [5, np.nan, 1, np.nan]])

print("Is the array missing data: ")
print(np.isnan(array))

Is the array missing data: 
[[False False  True False]
 [False False False False]
 [False  True False  True]]
